apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  namespace: default
  labels:
    app: petclinic
spec:
  selector:
    app: petclinic
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP